### ISSUE TITLE
[BUG] Consumer gets old offset when it joins consumer group

### ISSUE THREAD

**Issue by utahkay** [streamnative/kop#1289]
**Describe the bug**
I have a long-running test that has three consumers in a consumer group, every 40 minutes it stops one consumer, then 20 minutes later adds a new consumer to the group. So every 40 minutes there is a new consumer.
The new consumer often gets an old offset.

**To Reproduce**
pulsar-cloud:2.9.2.16
pulsar-protocol-handler-kafka-2.9.2.16.nar
sncloud-staging ('eagle' poolmember) 

1. Start three Kafka consumers in the same group.
    a. The consumers are configured with auto.offset.reset=earliest, enable.auto.commit=false. 
    b. The consumers call commitSync() after each message is received.
2. Start a Kafka producer and produce messages to the topic.
3. Stop a consumer, wait a few minutes.
4. Add a new consumer to the group, wait a few minutes.
5. Repeat (stop a consumer, wait, add a consumer).

**Expected behavior**
Expect the new consumer always to start at the last committed offset.
Instead, the new consumer often starts at an older offset. Over time this causes the consumers to receive thousands of duplicate messages.

**Screenshots**
Consumers receive more messages than the producer sends. Many duplicate messages received.
![image](https://user-images.githubusercontent.com/41346/168887294-cb60bc93-9e8c-4a43-a5f3-d9cdb3ca3d07.png)

**Additional context**
My client source code: https://github.com/streamnative/continuous-verification/tree/master/workers/kop-produce-consume/app/src
Running with this config:
```
    acceptableKafkaReceiveLatencyMs: 750
    **consumerGroupRebalanceIntervalMs: 1200000**
    **doConsumerGroupRebalance: true**
    elasticSearchUrl: null
    heartbeatServiceAccount: sa-continuous-verification@cv-pulsar.auth.test.cloud.gcp.streamnative.dev
    kafkaBootstrapServers: null
    kafkaConsumer:
      autoCommitIntervalMs: 500
      **enableAutoCommit: false**
      groupId: kop-produce-consume
    kafkaProducer:
      acks: all
      clientId: kop-produce-consume
    metricsPort: 8080
    produceIntervalMs: 5000
    pulsarClient:
      oauthAudience: urn:sn:pulsar:cv-pulsar:test-2-9-kop2
      oauthCredentialsUrl: file:///var/creds/service-account.json
      oauthCredentialsUrlAdmin: file:///var/admincreds/admin-service-account.json
      oauthIssuerUrl: https://auth.sncloud-stg.dev/
      serviceUrl: pulsar+ssl://test-2-9-kop2-49eea6ed-86f7-472a-8ac5-29787c6ee3cd.gcp-shared-gcp-usce1-eagle.streamnative.g.sn3.dev:6651
      serviceUrlAdmin: https://test-2-9-kop2-49eea6ed-86f7-472a-8ac5-29787c6ee3cd.gcp-shared-gcp-usce1-eagle.streamnative.g.sn3.dev
    target: test-2-9-kop
    targetNamespace: cv-pulsar
    topic: public/default/partitioned-topic
```
