### ISSUE TITLE
[FEATURE] Skip tests CI for docs PR

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#997]
**Is your feature request related to a problem? Please describe.**
There is no need to run tests when the PR is only for docs.

**Describe the solution you'd like**
Add the file change check script like what [Pulsar's Github workflows](https://github.com/apache/pulsar/tree/master/.github/workflows) do.

```yaml
      - name: Check changed files
        id: check_changes
        run: echo "::set-output name=docs_only::${{ fromJSON(steps.changes.outputs.all_count) == fromJSON(steps.changes.outputs.docs_count) && fromJSON(steps.changes.outputs.docs_count) > 0 }}"
```
